-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 16:54:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ibratef
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ibratef` ;

-- -----------------------------------------------------
-- Schema ibratef
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ibratef` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ibratef` ;

-- -----------------------------------------------------
-- Table `ibratef`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel` INT NOT NULL DEFAULT '2' COMMENT '1=Super Administrador; 11=Administador; 21=Usuário',
  `nome` VARCHAR(60) CHARACTER SET 'latin1' NOT NULL,
  `email` VARCHAR(150) CHARACTER SET 'latin1' NOT NULL,
  `senha` VARCHAR(250) CHARACTER SET 'latin1' NOT NULL,
  `statusRegistro` INT NOT NULL DEFAULT '1' COMMENT '1=Ativo; 2=Inativo; 3=Bloqueado;',
  PRIMARY KEY USING BTREE (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ibratef`.`agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`agendamento` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`agendamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `tipo_servico_id` INT NULL DEFAULT NULL,
  `animal_id` INT NULL DEFAULT NULL,
  `funcionario_id` INT NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  `animal` VARCHAR(50) NOT NULL,
  `usuario_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tipo_servico_id` (`tipo_servico_id` ASC) VISIBLE,
  INDEX `funcionario_id` (`funcionario_id` ASC) VISIBLE,
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ibratef`.`usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `ibratef`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`categoria` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `statusRegistro` VARCHAR(45) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ibratef`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`cidade` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `uf_id` INT NOT NULL,
  `codIBGE` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_uf_id` (`nome` ASC, `uf_id` ASC) VISIBLE,
  INDEX `FK1_cidade_uf_id` (`uf_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ibratef`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`cliente` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `statusRegistro` INT NULL DEFAULT '1' COMMENT 'Ativo ou Inativo',
  `usuario_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `unique_telefone` (`telefone` ASC) VISIBLE,
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ibratef`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ibratef`.`historico_atendimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`historico_atendimento` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`historico_atendimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `tipo_servico_id` INT NULL DEFAULT NULL,
  `animal_id` INT NULL DEFAULT NULL,
  `funcionario_id` INT NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tipo_servico_id` (`tipo_servico_id` ASC) VISIBLE,
  INDEX `animal_id` (`animal_id` ASC) VISIBLE,
  INDEX `funcionario_id` (`funcionario_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ibratef`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`produto` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(150) NULL DEFAULT NULL,
  `cate_id` INT NOT NULL,
  `precoVenda` DECIMAL(10,2) NOT NULL,
  `statusRegistro` INT NULL DEFAULT '1',
  `imgproduto` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1_produto_cate_id` (`cate_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ibratef`.`tipo_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`tipo_servico` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`tipo_servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `imgservico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ibratef`.`uf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`uf` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`uf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(2) NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `bandeira` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sigla` (`sigla` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ibratef`.`usuariorecuperasenha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ibratef`.`usuariorecuperasenha` ;

CREATE TABLE IF NOT EXISTS `ibratef`.`usuariorecuperasenha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `chave` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `statusRegistro` INT NOT NULL DEFAULT '1' COMMENT '1=Ativo;2=Inativo',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`),
  UNIQUE INDEX `chave` USING BTREE (`chave`) VISIBLE,
  INDEX `FK1_usuariorecuperacaosenha` USING BTREE (`usuario_id`) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
